language: java
sudo: true
jdk:
  - openjdk8
after_success:
  - chmod +x discord.sh
  - ./discord.sh success $WEBHOOK_URL
after_failure:
  - chmod +x discord.sh
  - ./discord.sh failure $WEBHOOK_URL
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true