language: java
sudo: true
jdk:
- openjdk8
after_success:
- chmod +x discord.sh
- "./discord.sh success $WEBHOOK_URL"
after_failure:
- chmod +x discord.sh
- "./discord.sh failure $WEBHOOK_URL"
deploy:
  provider: releases
  api_key:
    secure: m0AwHXcZ15FJts9pNBwQHIFcYGtxy486Zbvt4K8juNEY057PvtrpSZbg3PK37gIvFn5YYy7QE45nWRAGoqFBHhk74ibcRF+CgvbROz24CPEg0dv7e+63fJAAObBNVkWZf1kaIKNn3MQSWMbtj7f48HSRNUgWfTxaX6hLuB5RGO/CC0ADoQ/84TFdRFFELODcQJZD9dikr1S152JM3L2Gmb+FDudl8mjD+fncpwlVE15TxYKcxDimqbztJAACtVDBfA6kshVdCZ0VXyuTkiO0mU57qEaconss4v/SWom0SnIoaRh0IWKa9SVidTY7pkwMY/aWxo+kmPBCix3D+QVDZKbDWNzIBTUoBDbrdSM8Q265+7Qyx5zJAbHIFfIwrPXk39MspbmR6xNBIhLiVsmKwV4npN0NVBCglC2y2SSECoDv0nOKbApfCjTRj7C+vlIA3t88aSllClZa3Sl2Ni8HOdciTRQKJYElFoEhOf0RBeg5kmy0yvyFOzubeD/26ekrqyKbbd8O2gYuLVD2gXT/floz0mw3l2PFH/+DUJjSltoX9KMy6LSsDaNrJiEL7/qCz4ot7s/VegI/PPWcduR0oX1mIpmgYBUrJf+jGBa7mg/8NRzqxrQK9fUYWWbnQ7JfkjhfSEeLHortT3NIqS8rADef9NRmzaZ6GuOXFz52M9I=
  file: directory/*
  on:
    repo: nemosrc/webhook-test
